# Generated by Django 3.0.8 on 2020-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articlewrite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articlebuy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.CreateModel(
            name='articlesale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Article',
            new_name='articlefree',
        ),
    ]
